serverUrl: http://lyrio.test/
key: 40uXJPXzuO2Ha41iuh8Pjw1h0ahvP9i/zJk7Rtn/
dataStore: /root/judge/data
binaryCacheStore: /root/judge/cache
binaryCacheMaxSize: 536870912
taskConsumingThreads: 2
maxConcurrentDownloads: 10
maxConcurrentTasks: 3
taskWorkingDirectories:
  - /root/judge/1
  - /root/judge/2
  - /root/judge/3
sandbox:
  rootfs: /opt/rootfs-ng
  user: sandbox
  hostname: null
  environments:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    HOME: /sandbox
    LC_ALL: en_US.UTF-8
